import { motion } from 'motion/react';
import { ChevronLeft, Download, Send, Copy, FileText, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

import { Language, translations } from '../../lib/locales';

export default function ReportPreviewScreen({ 
  report, 
  lang,
  onBack,
  onComplete
}: { 
  report: any, 
  lang: Language,
  onBack: () => void,
  onComplete: () => void
}) {
  const t = translations[lang];
  const [isCopied, setIsCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const handleCopy = () => {
    if (!report) return;
    navigator.clipboard.writeText(report.generatedContent);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleExportPDF = async () => {
    if (!report) return;
    setIsExporting(true);
    const element = document.getElementById('report-content');
    if (!element) return;

    try {
      const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#050505' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`SupportHub-Report-${report.id}.pdf`);
    } catch (e) {
      console.error(e);
    } finally {
      setIsExporting(false);
    }
  };

  if (!report) return null;

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className={`flex-1 overflow-y-auto px-6 pt-16 pb-32 ${lang === 'ps' ? 'text-right' : 'text-left'}`}
      dir={lang === 'ps' ? 'rtl' : 'ltr'}
    >
      <header className={`flex items-center justify-between mb-8 ${lang === 'ps' ? 'flex-row-reverse' : ''}`}>
        <div className={`flex items-center gap-4 ${lang === 'ps' ? 'flex-row-reverse' : ''}`}>
          <button onClick={onBack} className="p-2 -ml-2 rounded-xl active:bg-white/5">
            <ChevronLeft className={`w-6 h-6 ${lang === 'ps' ? 'rotate-180' : ''}`} />
          </button>
          <h3 className="text-2xl font-bold font-display">{lang === 'ps' ? 'کتنه' : 'Preview'}</h3>
        </div>
        <div className="px-3 py-1 bg-brand-soft border border-brand-soft rounded-full">
          <span className="text-brand text-xs font-bold uppercase tracking-wider">{report.status}</span>
        </div>
      </header>

      <div className="space-y-6">
        <div id="report-content" className="glass-card p-6 min-h-[400px]" style={{ backgroundColor: '#09090b', border: '1px solid rgba(255,255,255,0.1)' }}>
          <div className={`flex items-center gap-3 mb-6 pb-4 ${lang === 'ps' ? 'flex-row-reverse' : ''}`} style={{ borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
            <div className="w-10 h-10 rounded-xl flex items-center justify-center bg-brand-soft">
              <FileText className="w-5 h-5 text-brand" />
            </div>
            <div className={lang === 'ps' ? 'text-right' : 'text-left'}>
              <h4 className="font-bold" style={{ color: '#ffffff' }}>{report.reportType} Report</h4>
              <p className="text-gray-500 text-xs text-nowrap" style={{ color: '#6b7280' }}>Generated by SupportHub AI</p>
            </div>
          </div>
          
          <div className={`markdown-body text-sm leading-relaxed whitespace-pre-wrap ${lang === 'ps' ? 'text-right' : 'text-left'}`} style={{ color: '#d1d5db' }}>
            <ReactMarkdown>{report.generatedContent}</ReactMarkdown>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <button 
            onClick={handleCopy}
            className="btn-glass"
          >
            {isCopied ? <CheckCircle2 className="w-5 h-5 text-brand" /> : <Copy className="w-5 h-5 text-gray-400" />}
            <span>{isCopied ? (lang === 'ps' ? 'کاپي شو' : 'Copied') : (lang === 'ps' ? 'متن کاپي کړئ' : 'Copy Text')}</span>
          </button>
          
          <button 
            onClick={handleExportPDF}
            disabled={isExporting}
            className="btn-glass"
          >
            {isExporting ? (
              <motion.div animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: "linear" }} className="w-5 h-5 border-2 border-white/20 border-t-white rounded-full" />
            ) : (
              <Download className="w-5 h-5 text-gray-400" />
            )}
            <span>{lang === 'ps' ? 'PDF ډاونلوډ' : 'Export PDF'}</span>
          </button>

          <button 
            onClick={onComplete}
            className="btn-primary col-span-2"
          >
            <Send className="w-5 h-5" />
            <span>{lang === 'ps' ? 'رپوټ لېږل' : 'Send Report Directly'}</span>
          </button>
        </div>
      </div>
    </motion.div>
  );
}
